[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arq>=0.28.0",
    "datasets>=3.0.0",
    "fastapi>=0.121.0",
    "label-studio-sdk>=2.1.0",
    "minio>=7.2.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.20",
    "redis>=5.3.1",
    "s3fs>=2024.9.0",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.34.0",
]
